# Macro file for the 
# initialization of G4GeneralParticleSource


/gps/energy ENERGY GeV
/gps/particle PARTICLE

/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 2 mm #0.01 mm #17.5 mm
/gps/pos/halfy 2 mm #0.01 mm #90 mm

#/gps/ang/type iso
#/gps/ang/mintheta 0.
#/gps/ang/maxtheta 0.3
#/gps/ang/minphi 0.
#/gps/ang/maxphi 1.570796

/gps/direction 0. 0. 1.

#/tracking/verbose 1
/run/beamOn NEVTS
